const projects = [
  {
    id: 'mirror',
    title: 'Mirror',
    img: '/mirror.png',
    link: '/projects/mirror',
    date: '2026',
    company: 'Next.js 16 / React 19 / Supabase',
    liveLink: 'https://mirroraidev.vercel.app',
    primary: '#09090b',
    accentColor: '#8b5cf6',
    secondary: '#18181b',
    fillColor: '#fafafa',
    menuColor: '#8b5cf6',
    menuFontColor: '#ffffff',
    fluidColor: '#8b5cf6',
    images: [
      {
        src: '/mirror.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Mirror es una herramienta SaaS de productividad para LinkedIn que inyecta una interfaz en la plataforma para la generación de comentarios con perfiles de voz personalizados.',
      'Está construida sobre una arquitectura fullstack altamente extensible con Next.js 16, React 19, TypeScript y Tailwind CSS v4, interactuando mediante APIs REST con su extensión de Chrome.',
      'La lógica de negocio y las suscripciones por niveles (Free, Pro, Elite) están integradas con Lemon Squeezy y encapsuladas en Edge Functions de Supabase (PostgreSQL + Auth).',
    ],
  },
  {
    id: 'livenotes',
    title: 'LiveNotes',
    img: '/livenotes.png',
    link: '/projects/livenotes',
    date: '2025',
    company: 'React / Python / Groq API',
    liveLink: 'https://play.google.com/store/apps/details?id=com.starholdings.livenotes',
    primary: '#0f172a',
    accentColor: '#3b82f6',
    secondary: '#1e293b',
    fillColor: '#f8fafc',
    menuColor: '#3b82f6',
    menuFontColor: '#ffffff',
    fluidColor: '#3b82f6',
    images: [
      {
        src: '/livenotes.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'LiveNotes es una aplicación móvil para la captura inteligente de notas con transcripción automática de audio y resúmenes estructurados mediante integración con modelos de IA (Groq API).',
      'Cuenta con una arquitectura de componentes limpia en frontend (React) y lógica de procesamiento de audio de alto rendimiento en servicios backend con Python.',
      'Implementa algoritmos de negocio complejos para la segmentación de transcripciones, indexación y extracción de puntos clave de forma automática.',
    ],
  },
  {
    id: 'vibes',
    title: 'Vibes',
    img: '/vibes.png',
    link: '/projects/vibes',
    date: '2025',
    company: 'Kotlin / Jetpack Compose',
    liveLink: 'https://github.com/jeanfes',
    primary: '#111827',
    accentColor: '#10b981',
    secondary: '#1f2937',
    fillColor: '#f9fafb',
    menuColor: '#10b981',
    menuFontColor: '#ffffff',
    fluidColor: '#10b981',
    images: [
      {
        src: '/vibes.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Vibes es una aplicación móvil de bienestar diseñada para ayudar a los usuarios a relajarse, concentrarse y dormir mejor.',
      'Ofrece una biblioteca de sonidos ambientales de alta calidad y un temporizador personalizable, construida de forma nativa con Jetpack Compose.',
      'Cuenta con rutinas personalizadas de relajación y una experiencia de usuario fluida e inmersiva adaptada a dispositivos Android.',
    ],
  },
  {
    id: 'alphabook',
    title: 'Alphabook',
    img: '/alphabook.png',
    link: '/projects/alphabook',
    date: '2024',
    company: 'React Native / Expo / TS',
    liveLink: 'https://github.com/jeanfes',
    primary: '#27272a',
    accentColor: '#f43f5e',
    secondary: '#3f3f46',
    fillColor: '#fafafa',
    menuColor: '#f43f5e',
    menuFontColor: '#ffffff',
    fluidColor: '#f43f5e',
    images: [
      {
        src: '/alphabook.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Alphabook es una biblioteca personal móvil desarrollada con React Native, Expo y TypeScript, pensada para la gestión eficiente de libros PDF.',
      'Permite a los usuarios organizar su colección digital de libros, realizar búsquedas rápidas, categorizar lecturas y leer sus documentos cómodamente en el celular.',
      'La app destaca por su diseño minimalista enfocado en la experiencia de lectura y navegación rápida.',
    ],
  },
  {
    id: 'tutorly',
    title: 'Tutorly',
    img: '/tutorly.png',
    link: '/projects/tutorly',
    date: '2024',
    company: 'React / CSS / JS',
    liveLink: 'https://github.com/jeanfes',
    primary: '#18181b',
    accentColor: '#8b5cf6',
    secondary: '#27272a',
    fillColor: '#f5f5f5',
    menuColor: '#8b5cf6',
    menuFontColor: '#ffffff',
    fluidColor: '#8b5cf6',
    images: [
      {
        src: '/tutorly.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Tutorly es una plataforma web dedicada a facilitar la conexión entre estudiantes y tutores para tutorías personalizadas.',
      'Construida con React, permite a los usuarios agendar citas, ver perfiles detallados de tutores y gestionar sesiones de aprendizaje de forma interactiva.',
      'Ofrece una interfaz amigable y responsiva optimizada para una navegación fluida entre dispositivos.',
    ],
  },
  {
    id: 'dermai',
    title: 'Dermai',
    img: '/dermai.png',
    link: '/projects/dermai',
    date: '2024',
    company: 'React / Node.js / MySQL',
    liveLink: 'https://github.com/jeanfes',
    primary: '#022c22',
    accentColor: '#06b6d4',
    secondary: '#064e3b',
    fillColor: '#f0fdfa',
    menuColor: '#06b6d4',
    menuFontColor: '#ffffff',
    fluidColor: '#06b6d4',
    images: [
      {
        src: '/dermai.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Dermai es una aplicación web enfocada en la atención dermatológica preliminar mediante inteligencia artificial y telemedicina.',
      'Desarrollada con React para el frontend, Node.js en el backend y MySQL como base de datos, ayuda a agendar citas y realizar pre-diagnósticos seguros.',
      'Garantiza una comunicación fluida entre pacientes y profesionales de la salud con un estricto manejo de privacidad.',
    ],
  },
  {
    id: 'athome',
    title: 'Athome',
    img: '/athome.png',
    link: '/projects/athome',
    date: '2024',
    company: 'React / CSS / JS',
    liveLink: 'https://github.com/jeanfes',
    primary: '#0c0a09',
    accentColor: '#f59e0b',
    secondary: '#1c1917',
    fillColor: '#fafaf9',
    menuColor: '#f59e0b',
    menuFontColor: '#ffffff',
    fluidColor: '#f59e0b',
    images: [
      {
        src: '/athome.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Athome es una plataforma web interactiva enfocada en la venta e intermediación de bienes inmuebles.',
      'Utiliza React para ofrecer un buscador avanzado, filtros detallados de precios, zonas y tipos de propiedad, así como galerías visuales inmersivas.',
      'Proporciona una experiencia premium de navegación para que los usuarios encuentren su hogar ideal sin fricciones.',
    ],
  },
  {
    id: 'portfolio',
    title: 'Portfolio Blog',
    img: '/portfolio.png',
    link: '/projects/portfolio',
    date: '2023',
    company: 'HTML / CSS / JS',
    liveLink: 'https://jeanfes.github.io/Portfolio/',
    primary: '#0f172a',
    accentColor: '#3fba7b',
    secondary: '#1e293b',
    fillColor: '#f8fafc',
    menuColor: '#3fba7b',
    menuFontColor: '#ffffff',
    fluidColor: '#3fba7b',
    images: [
      {
        src: '/portfolio.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Mi portafolio y blog personal previo, construido con HTML, CSS y JavaScript vainilla.',
      'Sirvió como escaparate para mis primeros desarrollos web y artículos de tecnología, destacando por su interactividad, animaciones de entrada y diseño responsivo sin frameworks.',
    ],
  },
];

export default projects;
