const projects = [
  {
    id: 'mirror',
    title: 'Mirror',
    img: '/projects/mirror/mirror-thumb.webp',
    link: '/projects/mirror',
    date: '2026',
    company: 'Next.js 16 / React 19 / Supabase',
    liveLink: 'https://mirroraidev.vercel.app',
    extensionLink: 'https://chromewebstore.google.com/detail/mirror-%E2%80%93-ai-comment-write/plbemjpagkgkppfmkbcldojghdojblhc',
    primary: '#09090b',
    accentColor: '#8b5cf6',
    secondary: '#18181b',
    fillColor: '#fafafa',
    menuColor: '#8b5cf6',
    menuFontColor: '#ffffff',
    fluidColor: '#8b5cf6',
    images: [
      {
        src: '/projects/mirror/mirror-webstore.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/mirror/mirror-home.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/mirror/mirror-features.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/projects/mirror/mirror-pricing.webp',
        tag: 'medium',
        isRight: true,
      },
    ],
    desc: [
      'Mirror es una herramienta SaaS de productividad para LinkedIn que inyecta una interfaz en la plataforma para la generación de comentarios con perfiles de voz personalizados. La extensión está publicada en la Chrome Web Store.',
      'Está construida sobre una arquitectura fullstack altamente extensible con Next.js 16, React 19, TypeScript y Tailwind CSS v4, interactuando mediante APIs REST con su extensión de Chrome (Plasmo).',
      'La lógica de negocio y las suscripciones por niveles (Free, Pro, Elite) están integradas con Lemon Squeezy y encapsuladas en Edge Functions de Supabase (PostgreSQL + Auth).',
    ],
  },
  {
    id: 'empleosremotoslatam',
    title: 'Empleos Remotos LATAM',
    img: '/projects/empleosremotoslatam/empleos-thumb.webp',
    link: '/projects/empleosremotoslatam',
    date: '2026',
    company: 'NestJS / Prisma / Next.js 16 / BullMQ',
    primary: '#0a0c10',
    accentColor: '#ff6a1f',
    secondary: '#41464e',
    fillColor: '#e6e6e3',
    menuColor: '#ff6a1f',
    menuFontColor: '#ffffff',
    fluidColor: '#ff6a1f',
    images: [
      {
        src: '/projects/empleosremotoslatam/empleos-home.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/empleosremotoslatam/empleos-vacantes.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/empleosremotoslatam/empleos-precios.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/projects/empleosremotoslatam/empleos-como-funciona.webp',
        tag: 'medium',
        isRight: true,
      },
    ],
    desc: [
      'Empleos Remotos LATAM es un radar de empleo remoto por nicho para Latinoamérica: el usuario se suscribe solo con su correo a una categoría tech y recibe cada mañana un resumen de vacantes, sin crear cuenta ni contraseña.',
      'Construido como monorepo con Turborepo, expone una API en NestJS + Prisma sobre PostgreSQL con colas en BullMQ/Redis para el scraping y envío de los digests, y un frontend en Next.js 16 con React 19 y un sistema de diseño propio de estética retro-técnica.',
      'Comparte contratos de tipos entre frontend y backend mediante un paquete TypeScript interno, y aísla los servicios externos (pagos, envío de correo) detrás de un modo de desarrollo simulado para no depender de credenciales en local.',
    ],
  },
  {
    id: 'naudly',
    title: 'Naudly',
    img: '/projects/naudly/naudly-thumb.webp',
    link: '/projects/naudly',
    date: '2026',
    company: 'NestJS / Next.js 15 / Prisma / BullMQ',
    primary: '#0b1f1c',
    accentColor: '#10b981',
    secondary: '#1a2e2a',
    fillColor: '#f0fdf9',
    menuColor: '#10b981',
    menuFontColor: '#ffffff',
    fluidColor: '#10b981',
    images: [
      {
        src: '/projects/naudly/naudly-home.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/naudly/naudly-panel.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/naudly/naudly-conversaciones.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/naudly/naudly-devoluciones.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/projects/naudly/naudly-analiticas.webp',
        tag: 'medium',
        isRight: true,
      },
      {
        src: '/projects/naudly/naudly-entrenamiento.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/projects/naudly/naudly-campanas.webp',
        tag: 'medium',
        isRight: true,
      },
    ],
    desc: [
      'Naudly es un dashboard SaaS de atención al cliente con IA para ecommerce en LATAM: centraliza conversaciones de WhatsApp e Instagram, gestiona devoluciones y cambios post-compra, y dispara campañas de recuperación de carrito y referidos al cerrar cada caso.',
      'El panel real cubre todo el ciclo de soporte: bandeja de conversaciones donde la IA responde y el agente puede tomar control, gestión de devoluciones con estados (solicitado, en revisión, completado), entrenamiento del asistente por base de conocimiento y políticas, y analíticas de resolución por IA vs. equipo humano.',
      'Es un monorepo con una API en NestJS, autenticación JWT y colas BullMQ/Redis, una web en Next.js 15/React 19 con un sistema de diseño propio de más de 200 componentes sobre Radix UI y CVA, y contratos Zod compartidos como fuente de verdad de tipos entre frontend y backend.',
      'Un modo sandbox simula por completo las integraciones externas (WhatsApp, Shopify, Tiendanube, Wompi, IA) con la forma real de sus APIs, permitiendo levantar y probar el producto completo sin credenciales de terceros.',
    ],
  },
  {
    id: 'cumbi',
    title: 'Cumbi',
    img: '/projects/cumbi/cumbi-thumb.webp',
    link: '/projects/cumbi',
    date: '2026',
    company: 'NestJS / Prisma / Next.js / Expo',
    primary: '#0f172a',
    accentColor: '#29b9f2',
    secondary: '#1e293b',
    fillColor: '#ffffff',
    menuColor: '#29b9f2',
    menuFontColor: '#ffffff',
    fluidColor: '#29b9f2',
    images: [
      {
        src: '/projects/cumbi/cumbi-home.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/cumbi/cumbi-servicios.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/cumbi/cumbi-profesional.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Cumbi es una plataforma SaaS de reservas para negocios que venden tiempo, espacio o cupos —citas, canchas, clases— donde el cliente reserva sin crear cuenta, identificándose solo con su número de teléfono.',
      'Está construida como monorepo con una API en NestJS + Prisma, una web en Next.js y una app móvil nativa en Expo/React Native, compartiendo lógica de negocio entre las tres superficies.',
      'El modelo de datos unifica citas, reservas de espacio y membresías de gimnasio bajo un mismo motor de disponibilidad, cobros y cancelaciones, adaptando el flujo de reserva paso a paso según el tipo de negocio.',
    ],
  },
  // LiveNotes: fuera temporalmente — le falta contenido (más capturas, detalle).
  // Se recupera del historial de git cuando esté lista para publicarse de nuevo.
];

export default projects;
